version: '3.1'

services:
  swagger:
    # https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md
    image: swaggerapi/swagger-ui:v4.17.1
    volumes:
      - ./swagger-vite/public/openapi.json:/app/swagger.json
    ports:
      - 3001:8080
